name: Ryan Kiley
favicon: null
layout_spectrum: 0.6904646088369191
typography_spectrum: 0.08045916631817818
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.6013368957210332
  lightness: 0.06726706773042679
  saturation: 0.8766273346263915
  rhythmicContrast: 0.43078905576840043
purpose: []
